services:
  - type: web
    name: mssql-service
    repo: https://github.com/rachelyWinter/DB-with-docker
    branch: master
    env:
      - key: ACCEPT_EULA
        value: "Y"
      - key: SA_PASSWORD
        value: "Foir100#"
    buildCommand: docker build -t foyer-db-image .
    startCommand: docker run -e ACCEPT_EULA=Y -e SA_PASSWORD=Foir100# -p 1433:1433 foyer-db-image
